### ISSUE TITLE
双方向ペイメントチャネルの図

### ISSUE THREAD

**Issue by ghost** [blockchain-programming/book#1]
図11.2 双方向ペイメントチャネルの流れについての質問

1.コミットメントトランザクションB1作成するために、①のタイミングでアリスの公開鍵をボブに渡す必要があるのではないか？
2.①の後のオープニングトランザクションから右に出ている矢印は不要ではないか？
3.②でアリストボブがSecretから生成した結果を交換せずに済む方法は可能でしょうか？以下URLのFigure8以降の解説では、2つの異なるSecretから同一のRevocationKeyを生成しており鍵の交換が不要なように読めたので、このスキームとの違いが気になりました。https://github.com/bitcoinbook/bitcoinbook/blob/develop/ch12.asciidoc
4.「⑦シークレット交換」は「⑥コミットメントトランザクション交換」の前にすべきではないか？⑥と⑦の間に、ボブがコミットメントトランザクションB1を放送する可能性があるため。
5.コミットメントトランザクション1は払い戻しトランザクション(OUT1:5BTC,OUT2:5BTC)にした方が理解しやすいのではないでしょうか？チャネル未開設で残高が動いているのは違和感があるため。(今のままでも動きに問題はないと思います)

**Comment by shuntaro-tanaka** [comment]
＞1
ご指摘の通りです。アリスとボブは、それぞれの公開鍵またはアドレスを互いに交換する必要があります。

＞2
コミットメントトランザクションB1を作成する際にオープニングトランザクションの情報が必要なため、矢印を記載しています。矢印がない場合、ボブは、オープニングトランザクションのインプットに指定されているアリスのUTXOを知ることができず、コミットメントトランザクションB1を作成できません。

＞3
失効鍵は両者で異なるものを生成します。失効鍵を使用するスキームにおいても、失効公開鍵の生成に必要な情報（Secretから生成した結果）を相手に渡す、失効秘密鍵の生成に必要な情報（Secret）を相手に渡す、という工程があるため、書籍の手順と変わらない手順となります。

＞4
⑥と⑦は同時に行う必要があります。シークレット交換を先に行った後にコミットメントトランザクションの交換が拒否された場合、以前の取引が無効となってしまいます。

＞5
ご指摘の通り、初めに払い戻しトランザクションを作成する方が理解しやすいと思いました。図11.2では、チャネルを開設するタイミング＝1回目の支払いのタイミングと考え、コミットメントトランザクション1が払い戻しと1回目の支払いを兼ねている形で記載しました。
