### ISSUE TITLE
Bitcoin::Protocol::Tx#verify_input_signature に渡す引数

### ISSUE THREAD

**Issue by cleemy-desu-wayo** [blockchain-programming/book#2]
Chapter06の `Bitcoin::Protocol::Tx#verify_input_signature` を使用している箇所（書籍ではP.158）で

> #0番目のアウトプットについて署名を検証

とあるのですが、こちらは「UTXOが含まれるトランザクション」においてではなく新しく生成したトランザクション（これから署名しようとしているトランザクション）においては、「0番目のインプットについて署名を検証」という理解であってますでしょうか？

bitcoin-rubyのソースでは、`#verify_input_signature` に渡す最初の引数をインデックスとして `@ in` という Array を参照しているようです。
https://github.com/lian/bitcoin-ruby/blob/0a90a568bfb791c3a437da3a7a99a90a319f4e46/lib/bitcoin/protocol/tx.rb#L315
ちなみに `@ in` の各要素は `Bitcoin::Protocol::TxIn` のインスタンスで、`TxIn` には `prev_out_index` というアクセサがあるようです。
https://github.com/lian/bitcoin-ruby/blob/0a90a568bfb791c3a437da3a7a99a90a319f4e46/lib/bitcoin/protocol/txin.rb#L15

**Comment by azuchi** [comment]
> 「0番目のインプットについて署名を検証」という理解であってますでしょうか？

はい。合ってます。UTXOを使用するトランザクション、つまりそのUTXOをインプットとして作られたトランザクションの署名を検証します。

**Comment by cleemy-desu-wayo** [comment]
ありがとうございます。

ところで

> （これから署名しようとしているトランザクション）

という言い方は変でしたね。
「署名したばかりのトランザクション（を複製したもの）」であると同時に「これからブロードキャストする予定のトランザクション（を複製したもの）」ですね。
